#!/usr/bin/env python3
"""Emit configs/experiments/diffsbdd_nsamples50_subset10.yaml: top-10 pockets by original validity from n=20 metrics CSV."""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml

_REPO = Path(__file__).resolve().parent.parent


def _load_real47_pockets() -> dict[str, dict]:
    ypath = _REPO / "configs" / "experiments" / "pocket2mol_real47.yaml"
    with open(ypath, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    out: dict[str, dict] = {}
    for e in cfg.get("pockets", []):
        out[str(e["id"]).upper()] = e
    return out


def main() -> int:
    metrics = _REPO / "data" / "results" / "metrics_per_condition__run1778615375.csv"
    example = _REPO / "configs" / "examples" / "diffsbdd.example.yaml"
    out_path = _REPO / "configs" / "experiments" / "diffsbdd_nsamples50_subset10.yaml"

    df = pd.read_csv(metrics)
    orig = df[df["perturbation_tag"].astype(str) == "original"].copy()
    orig = orig.sort_values("validity", ascending=False, kind="mergesort")
    pids = [str(x).strip() for x in orig["pocket_id"].drop_duplicates().head(10).tolist()]

    pmap = _load_real47_pockets()
    pockets_yaml: list[dict] = []
    for pid in pids:
        key = pid.upper()
        if key not in pmap:
            raise KeyError(f"Pocket {pid!r} not in configs/experiments/pocket2mol_real47.yaml")
        ent = pmap[key]
        pdb_rel = ent["pdb"]
        pockets_yaml.append(
            {
                "id": pid,
                "pdb": pdb_rel,
                "ligand_chain": str(ent["ligand_chain"]),
                "ligand_resseq": int(ent["ligand_resseq"]),
                "full_pdb": ent.get("full_pdb", pdb_rel),
                "ref_ligand": ent.get(
                    "ref_ligand",
                    f'{ent["ligand_chain"]}:{ent["ligand_resseq"]}',
                ),
            }
        )

    with open(example, encoding="utf-8") as f:
        ex = yaml.safe_load(f)

    cfg = {
        "project_root": ".",
        "seed": int(ex.get("seed", 0)),
        "run_id": "diffsbdd_nsamples50_subset10",
        "paths": ex["paths"],
        "extraction_radius": 8.0,
        "brittleness_std_threshold": 0.05,
        "skip_failed_pockets": False,
        "invariant_tags": [
            "atom_shuffle",
            "coordinate_jitter",
            "crop_radius_plus_1.5",
            "crop_radius_minus_1.5",
        ],
        "pockets": pockets_yaml,
        "perturbations": [
            {"tag": "original", "type": "identity"},
            {"tag": "atom_shuffle", "type": "atom_shuffle", "seed": 0},
            {
                "tag": "coordinate_jitter",
                "type": "coordinate_jitter",
                "sigma": 0.1,
                "seed": 1,
            },
            {
                "tag": "crop_radius_plus_1.5",
                "type": "crop_radius_plus",
                "delta_angstrom": 1.5,
            },
            {
                "tag": "crop_radius_minus_1.5",
                "type": "crop_radius_minus",
                "delta_angstrom": 1.5,
            },
        ],
        "model": dict(ex["model"]),
    }
    cfg["model"]["n_samples"] = 50

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "# Generated by scripts/generate_nsamples50_subset_config.py — re-run to refresh pocket list.\n"
        )
        yaml.dump(cfg, f, sort_keys=False, default_flow_style=False)

    print(f"Wrote {out_path} with pockets (by validity): {pids}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
