#!/usr/bin/env python3
"""Generate configs/experiments/diffsbdd_meaningful_real20.yaml from DiffSBDD metrics CSV + real47 pocket table."""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml

from sbdd_robust.datasets.find_nearest_residue import find_nearest_residue_id

_REPO = Path(__file__).resolve().parent.parent


def _load_real47_pockets() -> dict[str, dict]:
    ypath = _REPO / "configs" / "experiments" / "pocket2mol_real47.yaml"
    with open(ypath, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    out: dict[str, dict] = {}
    for e in cfg.get("pockets", []):
        out[str(e["id"]).upper()] = e
    return out


def main() -> int:
    metrics = _REPO / "data" / "results" / "metrics_per_condition__run1778615375.csv"
    example = _REPO / "configs" / "examples" / "diffsbdd.example.yaml"
    out_path = _REPO / "configs" / "experiments" / "diffsbdd_meaningful_real20.yaml"

    df = pd.read_csv(metrics)
    orig = df[df["perturbation_tag"].astype(str) == "original"].copy()
    orig = orig[pd.to_numeric(orig["n_valid"], errors="coerce").fillna(0) > 0]
    pids = [str(x).strip() for x in orig["pocket_id"].tolist()[:20]]

    pmap = _load_real47_pockets()
    pockets_yaml: list[dict] = []
    for pid in pids:
        key = pid.upper()
        if key not in pmap:
            raise KeyError(f"Pocket {pid!r} not in configs/experiments/pocket2mol_real47.yaml")
        ent = pmap[key]
        pdb_rel = ent["pdb"]
        pdb_abs = (_REPO / pdb_rel).resolve()
        if not pdb_abs.is_file():
            raise FileNotFoundError(f"Missing PDB {pdb_abs}")
        lc = str(ent["ligand_chain"])
        lr = int(ent["ligand_resseq"])
        mut_id = find_nearest_residue_id(pdb_abs, lc, lr)
        full_pdb = ent.get("full_pdb", pdb_rel)
        ref_lig = ent.get("ref_ligand", f"{lc}:{lr}")
        pockets_yaml.append(
            {
                "id": pid,
                "pdb": pdb_rel,
                "ligand_chain": lc,
                "ligand_resseq": lr,
                "full_pdb": full_pdb,
                "ref_ligand": ref_lig,
                "mutation_residue_id": mut_id,
            }
        )

    with open(example, encoding="utf-8") as f:
        ex = yaml.safe_load(f)

    cfg = {
        "project_root": ".",
        "seed": int(ex.get("seed", 0)),
        "run_id": "diffsbdd_meaningful_real20",
        "paths": ex["paths"],
        "extraction_radius": 8.0,
        "brittleness_std_threshold": 0.05,
        "skip_failed_pockets": True,
        "compute_docking": True,
        "vina_cpu": 4,
        "invariant_tags": ["meaningful_ala", "meaningful_trp"],
        "pockets": pockets_yaml,
        "perturbations": [
            {"tag": "original", "type": "identity"},
            {
                "tag": "meaningful_ala",
                "type": "residue_mutation",
                "target_aa": "A",
                "residue_id_from_pocket": True,
            },
            {
                "tag": "meaningful_trp",
                "type": "residue_mutation",
                "target_aa": "W",
                "residue_id_from_pocket": True,
            },
        ],
        "model": dict(ex["model"]),
    }
    cfg["model"]["n_samples"] = 20

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "# Generated by scripts/generate_meaningful_config.py — do not hand-edit without re-running.\n"
        )
        yaml.dump(cfg, f, sort_keys=False, default_flow_style=False)

    print(f"Wrote {out_path} with {len(pockets_yaml)} pockets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
